In [11]:
import pandas as pd
import numpy as np

ds_path = "Datos/lentes.csv"

try:
    df = pd.read_csv(ds_path, encoding="cp1252", delimiter=",")
    pd.set_option('display.float_format', '{:.4f}'.format)
    print(f"✅ Dataset cargado exitosamente!")
    print(f"\n🔍 Primeras 5 filas:")
    display(df.head(5))
except Exception as e:
    print(f"❌ Error al cargar: {e}")

✅ Dataset cargado exitosamente!

🔍 Primeras 5 filas:

   Id   Edad   Prescripcion Astigmatismo  Lagrimas     Diagnostico
0   1  Joven  Hipermetropía           NO    Normal  Lentes_Blandos
1   2  Joven         Miopía           NO    Normal  Lentes_Blandos
2   3  Joven  Hipermetropía           SI    Normal    Lentes_Duros
3   4  Joven         Miopía           SI    Normal    Lentes_Duros
4   5  Joven  Hipermetropía           NO  Reducida  No_usar_Lentes

In [12]:
df = df.drop(columns=["Id"])
df["Edad"] = df["Edad"].map({"Joven":1, "pre_presb":2, "Presbicia":3})
df["Prescripcion"] = df["Prescripcion"].map({"Miopía":1, "Hipermetropía":2})
df["Astigmatismo"] = df["Astigmatismo"].map({"NO":1, "SI":2})
df["Lagrimas"] = df["Lagrimas"].map({"Reducida":1, "Normal":2})
df["Diagnostico"] = np.where(df["Diagnostico"] == "Lentes_Blandos", 1, 0)

display(df)

    Edad  Prescripcion  Astigmatismo  Lagrimas  Diagnostico
0      1             2             1         2            1
1      1             1             1         2            1
2      1             2             2         2            0
3      1             1             2         2            0
4      1             2             1         1            0
5      1             2             2         1            0
6      1             1             1         1            0
7      1             1             2         1            0
8      2             2             1         2            1
9      2             1             2         2            0
10     2             1             1         2            1
11     2             2             2         1            0
12     2             2             1         1            0
13     2             2             2         2            0
14     2             1             1         1            0
15     2             1             2         1            0
16     3             1             2         2            0
17     3             2             1         2            1
18     3             2             1         1            0
19     3             2             2         1            0
20     3             2             2         2            0
21     3             1             1         1            0
22     3             1             1         2            0
23     3             1             2         1            0

In [20]:
import sys
import os

# Ruta absoluta a la carpeta "Fuentes"
ruta_fuentes = os.path.abspath(os.path.join(os.getcwd(), "Fuentes"))
sys.path.append(ruta_fuentes)

# Ahora podés importar
from ClassPerceptron import Perceptron


ppn = Perceptron(alpha=0.1, n_iter=200)

np.set_printoptions(suppress=True, precision=4)

X = df.drop(columns=["Diagnostico"]).to_numpy()
T = df["Diagnostico"].to_numpy()

ppn.fit(X,T)

X = df.drop(columns=["Diagnostico"]).to_numpy()
T = df["Diagnostico"].to_numpy()

Y = ppn.predict(X)
aciertos = np.sum(Y == T)

if (aciertos == T.size):
    print("Clasifico todo correctamente")
else:
    print("Solo clasifico",aciertos,"de",T.size)

print(aciertos)

Clasifico todo correctamente
24